/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@interface SBAppSwitcherController : NSObject 
{
	id _model;
	id _nowPlaying;
	id _bottomBar;
	SBApplicationIcon* _pushedIcon;
	BOOL _editing;
}

-(void)viewWillAppear;
-(void)viewDidDisappear;

@end

